Homework 2
================
Jenesis Merriman
October 5, 2022

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(readxl)
```

## Problem 1

The below code uses `readr` and `janitor::clean_names()` to import and
clean the data. It also uses `select` to retain line, station, name,
station latitude / longitude, routes served, entry, vending, entrance
type, and ADA compliance and and `mutate` to convert the entry variable
from character to a logical variable.

``` r
transit_data = read_csv(
  file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
  col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>%
  janitor::clean_names() %>%
  select(line, station_name, station_latitude,
         station_longitude, route1:route11, entry, vending,
         entrance_type, ada)  %>%
  mutate(entry = recode(entry, "YES" = TRUE, "NO" = FALSE))
```

This dataset focuses on NYC transit data and includes the variables
line, station, name, station latitude, station longitude, routes served,
entry, vending, entrance type, and ADA compliance. In order to clean the
data, I imported the data, updated variable types, cleaned variable
names, and selected the relevant columns. I then updated `entry` from
`yes` / `no` to a logical variable. The resulting data set is 1868 rows
x 19 columns. These data are not “tidy” in its current state. To further
tidy our data, we would need to convert `route` variables from wide to
long format.

**How many distinct stations are there?**

``` r
transit_data %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

*There are 465 distinct stations in the NYC transit system, according to
our dataset.*

**How many stations are ADA compliant?**

``` r
transit_data %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

*There are 84 ADA compliant stations in the NYC transit system,
according to our dataset.*

**What proportion of station entrances / exits without vending allow
entrance?**

``` r
transit_data %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

*The proportion of station entrances / exits without vending that allow
entrance is 0.377.*

**Reformat data so that route number and route name are distinct
variables. How many distinct stations serve the A train? Of the stations
that serve the A train, how many are ADA compliant?**

``` r
transit_data %>%
  pivot_longer(
    route1:route11,
    names_to = "route_number", 
    names_prefix = "route",
    values_to = "route_name") %>%
    filter(route_name == "A") %>%
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
transit_data %>%
  pivot_longer(
    route1:route11,
    names_to = "route_number", 
    names_prefix = "route",
    values_to = "route_name") %>%
  filter(route_name == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

*60 distinct stations serve the A train. Of these stations, 17 are ADA
compliant.*

## Problem 2

Read and clean the Mr. Trash Wheel sheet, adding the variable ‘sheet’ to
keep track of data for future combining:

``` r
mr_trash = read_excel(
  "data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "Mr. Trash Wheel", range = 
    "A2:N535") %>% 
  janitor::clean_names() %>%
  mutate(sports_balls = as.integer(sports_balls), dumpster = as.double(dumpster), sheet =
           "mister") %>%
  drop_na()
```

Import, clean, and organize the data for Professor Trash Wheel, adding
the variable ‘sheet’ to keep track of data for future combining::

``` r
prof_trash = read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", 
    sheet = "Professor Trash Wheel", range = "A2:N117") %>% 
  janitor::clean_names() %>%
  mutate(sports_balls = as.integer(sports_balls), sheet = "professor") %>%
  drop_na()
```

Combine the Professor Trash Wheel dataset with the Mr. Trash Wheel
dataset to produce a single tidy dataset:

``` r
trash_tidy = full_join(mr_trash, prof_trash)
```

    ## Joining, by = c("dumpster", "month", "year", "date", "weight_tons",
    ## "volume_cubic_yards", "plastic_bottles", "polystyrene", "cigarette_butts",
    ## "glass_bottles", "grocery_bags", "chip_bags", "sports_balls", "homes_powered",
    ## "sheet")

Write a paragraph about these data; you are encouraged to use inline R.
Be sure to note the number of observations in the resulting dataset, and
give examples of key variables. For available data, what was the total
weight of trash collected by Professor Trash Wheel? What was the total
number of sports balls collected by Mr. Trash Wheel in 2020?
